export interface Country {
    name: string;      // Angielska nazwa kraju
    name_pl: string;   // Polska nazwa kraju
    code: string;      // Kod kraju
}

export const COUNTRIES: Country[] = [
    { name: 'Afghanistan', name_pl: 'Afganistan', code: 'af' },
    { name: 'Albania', name_pl: 'Albania', code: 'al' },
    { name: 'Algeria', name_pl: 'Algieria', code: 'dz' },
    { name: 'Angola', name_pl: 'Angola', code: 'ao' },
    { name: 'Argentina', name_pl: 'Argentyna', code: 'ar' },
    { name: 'Armenia', name_pl: 'Armenia', code: 'am' },
    { name: 'Australia', name_pl: 'Australia', code: 'au' },
    { name: 'Austria', name_pl: 'Austria', code: 'at' },
    { name: 'Azerbaijan', name_pl: 'Azerbejdżan', code: 'az' },
    { name: 'Bahamas', name_pl: 'Bahamy', code: 'bs' },
    { name: 'Bangladesh', name_pl: 'Bangladesz', code: 'bd' },
    { name: 'Barbados', name_pl: 'Barbados', code: 'bb' },
    { name: 'Belarus', name_pl: 'Białoruś', code: 'by' },
    { name: 'Belgium', name_pl: 'Belgia', code: 'be' },
    { name: 'Belize', name_pl: 'Belize', code: 'bz' },
    { name: 'Benin', name_pl: 'Benin', code: 'bj' },
    { name: 'Bhutan', name_pl: 'Bhutan', code: 'bt' },
    { name: 'Bolivia', name_pl: 'Boliwia', code: 'bo' },
    { name: 'Bosnia and Herzegovina', name_pl: 'Bośnia i Hercegowina', code: 'ba' },
    { name: 'Botswana', name_pl: 'Botswana', code: 'bw' },
    { name: 'Brazil', name_pl: 'Brazylia', code: 'br' },
    { name: 'Bulgaria', name_pl: 'Bułgaria', code: 'bg' },
    { name: 'Burkina Faso', name_pl: 'Burkina Faso', code: 'bf' },
    { name: 'Burundi', name_pl: 'Burundi', code: 'bi' },
    { name: 'Cabo Verde', name_pl: 'Wyspy Zielonego Przylądka', code: 'cv' },
    { name: 'Cambodia', name_pl: 'Kambodża', code: 'kh' },
    { name: 'Cameroon', name_pl: 'Kamerun', code: 'cm' },
    { name: 'Canada', name_pl: 'Kanada', code: 'ca' },
    { name: 'Central African Republic', name_pl: 'Republika Środkowoafrykańska', code: 'cf' },
    { name: 'Chad', name_pl: 'Czad', code: 'td' },
    { name: 'Chile', name_pl: 'Chile', code: 'cl' },
    { name: 'China', name_pl: 'Chiny', code: 'cn' },
    { name: 'Colombia', name_pl: 'Kolumbia', code: 'co' },
    { name: 'Comoros', name_pl: 'Komory', code: 'km' },
    { name: 'Congo', name_pl: 'Kongo', code: 'cg' },
    { name: 'Costa Rica', name_pl: 'Kostaryka', code: 'cr' },
    { name: 'Croatia', name_pl: 'Chorwacja', code: 'hr' },
    { name: 'Cuba', name_pl: 'Kuba', code: 'cu' },
    { name: 'Cyprus', name_pl: 'Cypr', code: 'cy' },
    { name: 'Czech Republic', name_pl: 'Czechy', code: 'cz' },
    { name: 'Denmark', name_pl: 'Dania', code: 'dk' },
    { name: 'Djibouti', name_pl: 'Dżibuti', code: 'dj' },
    { name: 'Dominica', name_pl: 'Dominika', code: 'dm' },
    { name: 'Dominican Republic', name_pl: 'Dominikana', code: 'do' },
    { name: 'Ecuador', name_pl: 'Ekwador', code: 'ec' },
    { name: 'Egypt', name_pl: 'Egipt', code: 'eg' },
    { name: 'El Salvador', name_pl: 'Salwador', code: 'sv' },
    { name: 'Equatorial Guinea', name_pl: 'Gwinea Równikowa', code: 'gq' },
    { name: 'Eritrea', name_pl: 'Erytrea', code: 'er' },
    { name: 'Estonia', name_pl: 'Estonia', code: 'ee' },
    { name: 'Eswatini', name_pl: 'Eswatini', code: 'sz' },
    { name: 'Ethiopia', name_pl: 'Etiopia', code: 'et' },
    { name: 'Fiji', name_pl: 'Fidżi', code: 'fj' },
    { name: 'Finland', name_pl: 'Finlandia', code: 'fi' },
    { name: 'France', name_pl: 'Francja', code: 'fr' },
    { name: 'Gabon', name_pl: 'Gabon', code: 'ga' },
    { name: 'Gambia', name_pl: 'Gambia', code: 'gm' },
    { name: 'Georgia', name_pl: 'Gruzja', code: 'ge' },
    { name: 'Germany', name_pl: 'Niemcy', code: 'de' },
    { name: 'Ghana', name_pl: 'Ghana', code: 'gh' },
    { name: 'Greece', name_pl: 'Grecja', code: 'gr' },
    { name: 'Grenada', name_pl: 'Grenada', code: 'gd' },
    { name: 'Guatemala', name_pl: 'Gwatemala', code: 'gt' },
    { name: 'Guinea', name_pl: 'Gwinea', code: 'gn' },
    { name: 'Guinea-Bissau', name_pl: 'Gwinea Bissau', code: 'gw' },
    { name: 'Guyana', name_pl: 'Gujana', code: 'gy' },
    { name: 'Haiti', name_pl: 'Haiti', code: 'ht' },
    { name: 'Honduras', name_pl: 'Honduras', code: 'hn' },
    { name: 'Hungary', name_pl: 'Węgry', code: 'hu' },
    { name: 'Iceland', name_pl: 'Islandia', code: 'is' },
    { name: 'India', name_pl: 'Indie', code: 'in' },
    { name: 'Indonesia', name_pl: 'Indonezja', code: 'id' },
    { name: 'Iran', name_pl: 'Iran', code: 'ir' },
    { name: 'Iraq', name_pl: 'Irak', code: 'iq' },
    { name: 'Ireland', name_pl: 'Irlandia', code: 'ie' },
    { name: 'Israel', name_pl: 'Izrael', code: 'il' },
    { name: 'Italy', name_pl: 'Włochy', code: 'it' },
    { name: 'Jamaica', name_pl: 'Jamajka', code: 'jm' },
    { name: 'Japan', name_pl: 'Japonia', code: 'jp' },
    { name: 'Jordan', name_pl: 'Jordania', code: 'jo' },
    { name: 'Kazakhstan', name_pl: 'Kazachstan', code: 'kz' },
    { name: 'Kenya', name_pl: 'Kenia', code: 'ke' },
    { name: 'Kiribati', name_pl: 'Kiribati', code: 'ki' },
    { name: 'Korea', name_pl: 'Korea', code: 'kr' },
    { name: 'Kosovo', name_pl: 'Kosowo', code: 'xk' },
    { name: 'Kuwait', name_pl: 'Kuwejt', code: 'kw' },
    { name: 'Kyrgyzstan', name_pl: 'Kirgistan', code: 'kg' },
    { name: 'Laos', name_pl: 'Laos', code: 'la' },
    { name: 'Latvia', name_pl: 'Łotwa', code: 'lv' },
    { name: 'Lebanon', name_pl: 'Liban', code: 'lb' },
    { name: 'Lesotho', name_pl: 'Lesotho', code: 'ls' },
    { name: 'Liberia', name_pl: 'Liberia', code: 'lr' },
    { name: 'Libya', name_pl: 'Libia', code: 'ly' },
    { name: 'Liechtenstein', name_pl: 'Liechtenstein', code: 'li' },
    { name: 'Lithuania', name_pl: 'Litwa', code: 'lt' },
    { name: 'Luxembourg', name_pl: 'Luksemburg', code: 'lu' },
    { name: 'Madagascar', name_pl: 'Madagaskar', code: 'mg' },
    { name: 'Malawi', name_pl: 'Malawi', code: 'mw' },
    { name: 'Malaysia', name_pl: 'Malezja', code: 'my' },
    { name: 'Maldives', name_pl: 'Malediwy', code: 'mv' },
    { name: 'Mali', name_pl: 'Mali', code: 'ml' },
    { name: 'Malta', name_pl: 'Malta', code: 'mt' },
    { name: 'Marshall Islands', name_pl: 'Wyspy Marshalla', code: 'mh' },
    { name: 'Mauritania', name_pl: 'Mauretania', code: 'mr' },
    { name: 'Mauritius', name_pl: 'Mauritius', code: 'mu' },
    { name: 'Mexico', name_pl: 'Meksyk', code: 'mx' },
    { name: 'Micronesia', name_pl: 'Mikronezja', code: 'fm' },
    { name: 'Moldova', name_pl: 'Mołdawia', code: 'md' },
    { name: 'Monaco', name_pl: 'Monako', code: 'mc' },
    { name: 'Mongolia', name_pl: 'Mongolia', code: 'mn' },
    { name: 'Montenegro', name_pl: 'Czarnogóra', code: 'me' },
    { name: 'Morocco', name_pl: 'Maroko', code: 'ma' },
    { name: 'Mozambique', name_pl: 'Mozambik', code: 'mz' },
    { name: 'Myanmar', name_pl: 'Mjanma', code: 'mm' },
    { name: 'Namibia', name_pl: 'Namibia', code: 'na' },
    { name: 'Nauru', name_pl: 'Nauru', code: 'nr' },
    { name: 'Nepal', name_pl: 'Nepal', code: 'np' },
    { name: 'Netherlands', name_pl: 'Holandia', code: 'nl' },
    { name: 'New Zealand', name_pl: 'Nowa Zelandia', code: 'nz' },
    { name: 'Nicaragua', name_pl: 'Nikaragua', code: 'ni' },
    { name: 'Niger', name_pl: 'Niger', code: 'ne' },
    { name: 'Nigeria', name_pl: 'Nigeria', code: 'ng' },
    { name: 'North Macedonia', name_pl: 'Macedonia Północna', code: 'mk' },
    { name: 'Norway', name_pl: 'Norwegia', code: 'no' },
    { name: 'Oman', name_pl: 'Oman', code: 'om' },
    { name: 'Pakistan', name_pl: 'Pakistan', code: 'pk' },
    { name: 'Palau', name_pl: 'Palau', code: 'pw' },
    { name: 'Panama', name_pl: 'Panama', code: 'pa' },
    { name: 'Papua New Guinea', name_pl: 'Papua-Nowa Gwinea', code: 'pg' },
    { name: 'Paraguay', name_pl: 'Paragwaj', code: 'py' },
    { name: 'Peru', name_pl: 'Peru', code: 'pe' },
    { name: 'Philippines', name_pl: 'Filipiny', code: 'ph' },
    { name: 'Poland', name_pl: 'Polska', code: 'pl' },
    { name: 'Portugal', name_pl: 'Portugalia', code: 'pt' },
    { name: 'Qatar', name_pl: 'Katar', code: 'qa' },
    { name: 'Romania', name_pl: 'Rumunia', code: 'ro' },
    { name: 'Russia', name_pl: 'Rosja', code: 'ru' },
    { name: 'Rwanda', name_pl: 'Rwanda', code: 'rw' },
    { name: 'Saint Kitts and Nevis', name_pl: 'Saint Kitts i Nevis', code: 'kn' },
    { name: 'Saint Lucia', name_pl: 'Saint Lucia', code: 'lc' },
    { name: 'Saint Vincent and the Grenadines', name_pl: 'Saint Vincent i Grenadyny', code: 'vc' },
    { name: 'Samoa', name_pl: 'Samoa', code: 'ws' },
    { name: 'San Marino', name_pl: 'San Marino', code: 'sm' },
    { name: 'Sao Tome and Principe', name_pl: 'Wyspy Świętego Tomasza i Książęca', code: 'st' },
    { name: 'Saudi Arabia', name_pl: 'Arabia Saudyjska', code: 'sa' },
    { name: 'Senegal', name_pl: 'Senegal', code: 'sn' },
    { name: 'Serbia', name_pl: 'Serbia', code: 'rs' },
    { name: 'Seychelles', name_pl: 'Seszele', code: 'sc' },
    { name: 'Sierra Leone', name_pl: 'Sierra Leone', code: 'sl' },
    { name: 'Singapore', name_pl: 'Singapur', code: 'sg' },
    { name: 'Slovakia', name_pl: 'Słowacja', code: 'sk' },
    { name: 'Slovenia', name_pl: 'Słowenia', code: 'si' },
    { name: 'Solomon Islands', name_pl: 'Wyspy Salomona', code: 'sb' },
    { name: 'Somalia', name_pl: 'Somalia', code: 'so' },
    { name: 'South Africa', name_pl: 'Republika Południowej Afryki', code: 'za' },
    { name: 'South Sudan', name_pl: 'Sudan Południowy', code: 'ss' },
    { name: 'Spain', name_pl: 'Hiszpania', code: 'es' },
    { name: 'Sri Lanka', name_pl: 'Sri Lanka', code: 'lk' },
    { name: 'Sudan', name_pl: 'Sudan', code: 'sd' },
    { name: 'Suriname', name_pl: 'Surinam', code: 'sr' },
    { name: 'Sweden', name_pl: 'Szwecja', code: 'se' },
    { name: 'Switzerland', name_pl: 'Szwajcaria', code: 'ch' },
    { name: 'Syria', name_pl: 'Syria', code: 'sy' },
    { name: 'Tajikistan', name_pl: 'Tadżykistan', code: 'tj' },
    { name: 'Tanzania', name_pl: 'Tanzania', code: 'tz' },
    { name: 'Thailand', name_pl: 'Tajlandia', code: 'th' },
    { name: 'Timor-Leste', name_pl: 'Timor Wschodni', code: 'tl' },
    { name: 'Togo', name_pl: 'Togo', code: 'tg' },
    { name: 'Tonga', name_pl: 'Tonga', code: 'to' },
    { name: 'Trinidad and Tobago', name_pl: 'Trynidad i Tobago', code: 'tt' },
    { name: 'Tunisia', name_pl: 'Tunezja', code: 'tn' },
    { name: 'Turkey', name_pl: 'Turcja', code: 'tr' },
    { name: 'Turkmenistan', name_pl: 'Turkmenistan', code: 'tm' },
    { name: 'Tuvalu', name_pl: 'Tuvalu', code: 'tv' },
    { name: 'Uganda', name_pl: 'Uganda', code: 'ug' },
    { name: 'Ukraine', name_pl: 'Ukraina', code: 'ua' },
    { name: 'United Arab Emirates', name_pl: 'Zjednoczone Emiraty Arabskie', code: 'ae' },
    { name: 'United Kingdom', name_pl: 'Wielka Brytania', code: 'gb' },
    { name: 'United States', name_pl: 'Stany Zjednoczone', code: 'us' },
    { name: 'Uruguay', name_pl: 'Urugwaj', code: 'uy' },
    { name: 'Uzbekistan', name_pl: 'Uzbekistan', code: 'uz' },
    { name: 'Vanuatu', name_pl: 'Vanuatu', code: 'vu' },
    { name: 'Vatican City', name_pl: 'Watykan', code: 'va' },
    { name: 'Venezuela', name_pl: 'Wenezuela', code: 've' },
    { name: 'Vietnam', name_pl: 'Wietnam', code: 'vn' },
    { name: 'Yemen', name_pl: 'Jemen', code: 'ye' },
    { name: 'Zambia', name_pl: 'Zambia', code: 'zm' },
    { name: 'Zimbabwe', name_pl: 'Zimbabwe', code: 'zw' }
];
